version: '2'
services:

  db:
    image: mariadb:10.3.2
    container_name: blog_mariadb
    restart: always
    volumes:
      - ./docker/mysql/initdb/:/docker-entrypoint-initdb.d
      - ./docker/mysql/data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=blog
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=dinsorsee

  php:
    image: tutum/apache-php
    container_name: blog_apache
    restart: always
    environment:
      - ALLOW_OVERRIDE=true
    volumes:
      - ./:/app    
    ports:
      - "9000:80"

  pma:
      image: phpmyadmin/phpmyadmin
      container_name: blog_phpmyadmin
      restart: always
      ports:
        - "9001:80"
